FROM rocker/shiny
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y curl
RUN apt-get install -y gnupg2
RUN apt-get install -y libv8-3.14-dev

RUN R -e "install.packages(c('tidyr','dplyr','ggplot2','shinyjs','shinyjqui','DT','ggthemes','V8'), repos = 'http://cran.us.r-project.org')"
RUN R -e "source('http://www.bioconductor.org/biocLite.R'); biocLite('edgeR', ask=FALSE)"
COPY shiny-server.conf /etc/shiny-server

RUN echo "deb http://packages.cloud.google.com/apt cloud-sdk-$(lsb_release -c -s) main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
RUN apt-get update && sudo apt-get install -y google-cloud-sdk

RUN apt-get install -y fuse
RUN curl -L -O https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v0.23.0/gcsfuse_0.23.0_amd64.deb
RUN  dpkg --install gcsfuse_0.23.0_amd64.deb

RUN mkdir -p /var/log/shiny-server
RUN chown shiny:shiny /var/log/shiny-server

RUN mkdir -p /var/lib/shiny-server/bookmarks/
RUN chown -R shiny:shiny /var/lib/shiny-server/bookmarks

CMD /bin/shiny-server
